url:
baseurl:

# Site settings
title: Starfighter Farm
email: info@starfighterfarm.com
description: "Rebel Against Bland"


# Team names, titles and social links
people:
- name: Jim Howk
  pic: jim-astro2
  position:
  social:
    - title: twitter
      url: https://twitter.com/howkj1
    - title: facebook
      url: https://www.facebook.com/howkj1/


- name: Suzi Howk
  pic: suzi-astro
  position:
  social:
    - title: facebook
      url: https://www.facebook.com/profile.php?id=16925123

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://twitter.com/starfighterfarm
  - title: facebook
    url: https://www.facebook.com/starfighterfarm

# Postal address (add as many lines as necessary)
address:
  - line: PO Box 486
  - line: Slater, IA 50244

# Build settings
markdown: kramdown
permalink: pretty
