url:
baseurl:

# Site settings
title: Starfighter Farm
email: info@starfighterfarm.com
description: "Rebel Against Bland"


# Team names, titles and social links
people:
- name: Jim Howk
  pic: jim-astro
  position:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #


- name: Suzi Howk
  pic: suzi-astro
  position:
  social:
    - title: twitter
      url: #
    - title: facebook

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: PO Box 486
  - line: Slater, IA 50244

# Build settings
markdown: kramdown
permalink: pretty
